apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Values.pipeline.name | default "docker-image-ci-pipeline" }}
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: checkout
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: {{ .Values.pipeline.params.repoUrl | quote }}
        - name: revision
          value: {{ .Values.pipeline.params.revision | default "main" | quote }}

    - name: setup-python
      taskRef:
        name: setup-python
      runAfter: 
        - checkout
      params:
        - name: python-version
          value: {{ .Values.pipeline.params.pythonVersion | default "3.x" | quote }}
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: run-bandit-security-scan
      taskRef:
        name: run-bandit-security-scan
      runAfter:
        - setup-python
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: lint-with-flake8
      taskRef:
        name: lint-with-flake8
      runAfter:
        - run-bandit-security-scan
      params:
        - name: flake8-args
          value: {{ .Values.pipeline.params.flake8Args | default "--ignore=E302 --verbose ./app" | quote }}
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build-docker-image
      taskRef:
        name: build-docker-image
      runAfter:
        - lint-with-flake8
      params:
        - name: dockerfile
          value: {{ .Values.pipeline.params.dockerfile | default "Dockerfile" | quote }}
        - name: image-name
          value: {{ .Values.pipeline.params.imageName | default "my-image" | quote }}
      workspaces:
        - name: source
          workspace: shared-workspace
