apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-bandit-security-scan
spec:
  workspaces:
    - name: source
  steps:
    - name: install-bandit
      image: python:3.9-slim
      script: |
        pip install bandit
    - name: run-bandit
      image: python:3.9-slim
      script: |
        bandit ./app -r -x ./app/tests/